site_name: Wordle Docs
theme:
  features: navigation.indexes
  palette:
    scheme: slate
    primary: blue
    accent: cyan
    # Palette toggle for dark mode

  name: material

nav:
  - Home: index.md
  - Guide:
      - guide/Install.md
      - guide/Config.md
  - System:
      - Systems/Client.md
      - Systems/Server.md
